# Generated by Django 2.0.3 on 2018-04-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('mood_tag', models.CharField(max_length=20, verbose_name='心情标签')),
                ('content', models.TextField(verbose_name='内容')),
                ('pub_time', models.DateField(verbose_name='发表时间')),
            ],
        ),
    ]
